### ISSUE TITLE
Longitudinal Unique Event Name 

### ISSUE THREAD

**Issue by pys530** [draju/form-reviewer#1]
Hi draju,

Thanks for sharing the Form reviewer module!  It worked well for my team's needs.  Unfortunately, I was not able to get the module working for a longitudinal REDCap project.  The documentation mentioned typing in the unique event name for step 6 in the setup.  I am seeing a dropdown list of my project's field/variable names and unable to specify the event name.
![event name](https://user-images.githubusercontent.com/14205603/67603787-d896a200-f747-11e9-8928-5d5badd0d0a6.png)

I was testing the module on LTS 9.1.13 and 9.1.16.

Best regards.

**Comment by draju** [comment]
Thanks for the feedback!

So if I understand, you want to review a form that is part of a
longitudinal project?

If so, I think the module should work for that although I haven't tried it
recently.  Let's use a hypothetical example:

*Source project *

   - Includes a form called "Adverse Event Report"
   - A patient can have multiple adverse events, so you define an event for
   each possible up to some maximum number.  Let's say the unique event names
   (as listed in the "Define My Events" page) are: adverse_event_1,
   adverse_event_2, adverse_event_3, etc... up to adverse_event_10.

*Review project*

   - Include a form called "Adverse Event Review Form"
   - You may need to review each adverse event, but there may be AEs for
   multiple patients and each patient can have multiple events.  So your
   review form needs a text field to hold the patient's record ID (let's name
   the variable "record_link_field") and another text field to hold the event
   (let's name it "event_link_field").  I usually mark these fields
   with @HIDDEN-SURVEY so the reviewer doesn't see them.
   - When you set up the review, you have to pre-populate this information
   in the review form.  For example, to create a review for Patient #10,
   Adverse Event #2, you would enter record_link_field=10 and
   event_link_field=adverse_event_2

So in this scenario, you would choose "event_link_field" in the dropdown
for Step #6 - you are telling the module which variable contains the unique
event name.  But if this example is confusing, feel free to email me your
dictionaries for the source and review projects and I can take a look.

best,
Vishnu

**Comment by pys530** [comment]
Hi Vishnu,

Thanks for the detailed example!  That helps a lot and it looks great on
the longitudinal project.

Best regards,

Patrick Shi
